# Generated by Django 4.1.2 on 2022-10-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[(1, 'FOUNDATION'), (2, 'NON-GOVERNMENTAL ORGANIZATION'), (3, 'LOCAL COLLECTION')], default='FOUNDATION', max_length=2)),
                ('categories', models.ManyToManyField(to='user.category')),
            ],
        ),
    ]
