# Generated by Django 4.1.2 on 2022-10-12 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_time', models.TimeField(auto_created=True)),
                ('pick_up_date', models.DateField(auto_created=True)),
                ('quantity', models.PositiveIntegerField()),
                ('address', models.CharField(default='ul.Długa 44/4', max_length=128)),
                ('phone_number', models.IntegerField(max_length=12)),
                ('city', models.CharField(max_length=32)),
                ('zip_code', models.CharField(max_length=6)),
                ('pick_up_comment', models.TextField(max_length=1024)),
                ('categories', models.ManyToManyField(to='user.category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.institution')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
