# Generated by Django 4.1.2 on 2022-11-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_category_name_alter_institution_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='taken_time',
            field=models.DateTimeField(null=True),
        ),
    ]
